#!/bin/bash

n=$(( RANDOM % 100 ))
 if [[ n -eq 42 ]]; then
    echo "Something went wrong"
    >&2 echo "The error was using magic numbers"
    echo "successfully run count = $count before went wrong"
    exit 1
 fi

 count=$[ $count + 1 ]
 echo "Everything went according to plan"
